export const lightTheme = {
  mainBackground: "#f2f2f2",
  mainText: "#000",
  sidebarBackground: "#fff",
  sidebarText: "#000",
  headerBackground: "#fff",
  headerText: "#000",
  activeBackground: "#0077ff",
  activeText: "#fff",
  hoverBackground: "#f2f2f2",
  hoverText: "#000",
  mainContainerBackground: "#fff",
  buttonBackground: "#0077ff",
  buttonText: "#fff",
  buttonHoverBackground: "#2980b9",
  primaryColor: "#0077ff",

  primaryButtonBackground: "#0077ff",
  primaryButtonText: "#fff",
  primaryButtonHoverBackground: "#0077ff",

  secondaryButtonBackground: "#6c757d",
  secondaryButtonText: "#fff",
  secondaryButtonHoverBackground: "#5a6268",

  dangerButtonBackground: "red",
  dangerButtonText: "#fff",
  dangerButtonHoverBackground: "#c0392b",

  successButtonBackground: "#2ecc71",
  successButtonText: "#fff",
  successButtonHoverBackground: "#27ae60",

  warningButtonBackground: "#f39c12",
  warningButtonText: "#fff",
  warningButtonHoverBackground: "#d35400",
  inputBorder: "#f2f2f2",
  inputText: "#000",
  inputBackground: "#f2f2f2",
  inputFocusBorder: "#0077ff",
  inputFocusShadow: "rgba(0, 123, 255, 0.2)",
  inputHoverBorder: "#0077ff",
  inputHoverShadow: "rgba(0, 123, 255, 0.2)",
  inputPlaceholder: "#636c72",
  cardBackground: "#fff",
  cardText: "#000",
  cardBorder: "#fff",
  navbarBackground: "#0077ff",
  navbarText: "#fff",
  alertBackground: "#dff0d8",
  alertText: "#3c763d",
  alertBorder: "#d6e9c6",
  loaderBorder: "#555",
  loaderTop: "#0077ff",
  modalBackground: "#fff",
  modalText: "#333",
  tooltipBackground: "#0077ff",
  tooltipText: "#fff",
  tooltipIcon: "#555",
  toggleSwitchBackground: "#f2f2f2",
  toggleSwitchBackgroundActive: "#0077ff",
  toggleSwitchHandle: "#fff",
  toggleSwitchThumb: "#fff",
  accordionBorder: "#ddd",
  accordionHeaderBackground: "#f5f5f5",
  accordionHeaderText: "#333",
  progressBarBackground: "#eee",
  progressBarFill: "#0077ff",
  dropdownButtonBackground: "#0077ff",
  dropdownButtonText: "#fff",
  dropdownContentBackground: "#fff",
  tabsBackground: "#f5f5f5",
  tabsText: "#333",
  stepperBackground: "#f5f5f5",
  stepperText: "#333",
  carouselBackground: "#f5f5f5",
  badgeBackground: "#0077ff",
  badgeText: "#fff",
  tagBackground: "#0077ff",
  tagText: "#fff",
  toggleGroupBackground: "#f5f5f5",
  toggleGroupText: "#333",
  dividerColor: "#ddd",
  menuItemBackground: "#fff",
  menuItemText: "#333",
  menuItemHoverBackground: "#f5f5f5",
  menuItemHoverText: "#0077ff",
  notificationText: "#31708f",
  checkboxBackgroundChecked: "#0077ff",
  checkboxBorderChecked: "#0077ff",
  checkboxBorder: "#f2f2f2",
  checkboxCheckColor: "#fff",
  paginationBackground: "#f5f5f5",
  paginationText: "#333",
  loadingSpinnerBorder: "#f3f3f3",
  loadingSpinnerTopBorder: "#0077ff",
  linkText: "#0077ff",
  scrollbarThumb: "#888",
  scrollbarTrack: "#ddd",
  disabledBackground: "#eee",
  errorColor: "red",
  errorShadow: "rgba(255, 0, 0, 0.2)",
  dangerColor: "red",
  successColor: "#00cc00",
  infoColor: "#3399ff",
  warningColor: "#ffcc00",
  notificationBackground: "#fff",
};

export const darkTheme = {
  mainBackground: "#1a1a1a",
  mainText: "#fff",
  sidebarBackground: "#000",
  sidebarText: "#fff",
  headerBackground: "#000",
  headerText: "#fff",
  activeBackground: "#0077ff",
  activeText: "#fff",
  hoverBackground: "#1a1a1a",
  hoverText: "#fff",
  mainContainerBackground: "#1a1a1a",
  buttonBackground: "#0077ff",
  buttonText: "#fff",
  buttonHoverBackground: "#2980b9",
  primaryColor: "#0077ff",

  primaryButtonBackground: "#0077ff",
  primaryButtonText: "#fff",
  primaryButtonHoverBackground: "#0077ff",

  secondaryButtonBackground: "#6c757d",
  secondaryButtonText: "#fff",
  secondaryButtonHoverBackground: "#5a6268",

  dangerButtonBackground: "red",
  dangerButtonText: "#fff",
  dangerButtonHoverBackground: "#c0392b",

  successButtonBackground: "#2ecc71",
  successButtonText: "#fff",
  successButtonHoverBackground: "#27ae60",

  warningButtonBackground: "#f39c12",
  warningButtonText: "#fff",
  warningButtonHoverBackground: "#d35400",
  inputBorder: "#1a1a1a",
  inputText: "#fff",
  inputBackground: "#1a1a1a",
  inputFocusBorder: "#0077ff",
  inputFocusShadow: "rgba(0, 123, 255, 0.2)",
  inputHoverBorder: "#0077ff",
  inputHoverShadow: "rgba(0, 123, 255, 0.2)",
  inputPlaceholder: "#636c72",
  cardBackground: "#000",
  cardText: "#fff",
  cardBorder: "#000",
  navbarBackground: "#0077ff",
  navbarText: "#fff",
  alertBackground: "#2c2c2c",
  alertText: "#fff",
  alertBorder: "#555",
  loaderBorder: "#fff",
  loaderTop: "#0077ff",
  modalBackground: "#2c2c2c",
  modalText: "#fff",
  tooltipBackground: "#0077ff",
  tooltipText: "#fff",
  tooltipIcon: "#ccc",
  toggleSwitchBackground: "#333",
  toggleSwitchBackgroundActive: "#0077ff",
  toggleSwitchHandle: "#fff",
  toggleSwitchThumb: "#0077ff",
  accordionBorder: "#444",
  accordionHeaderBackground: "#2c2c2c",
  accordionHeaderText: "#fff",
  progressBarBackground: "#555",
  progressBarFill: "#0077ff",
  dropdownButtonBackground: "#0077ff",
  dropdownButtonText: "#fff",
  dropdownContentBackground: "#2c2c2c",
  tabsBackground: "#2c2c2c",
  tabsText: "#fff",
  stepperBackground: "#2c2c2c",
  stepperText: "#fff",
  carouselBackground: "#2c2c2c",
  badgeBackground: "#0077ff",
  badgeText: "#fff",
  tagBackground: "#0077ff",
  tagText: "#fff",
  toggleGroupBackground: "#2c2c2c",
  toggleGroupText: "#fff",
  dividerColor: "#555",
  menuItemBackground: "#2c2c2c",
  menuItemText: "#fff",
  menuItemHoverBackground: "#333",
  menuItemHoverText: "#0077ff",
  notificationText: "#ecf0f1",
  checkboxBackgroundChecked: "#0077ff",
  checkboxBorderChecked: "#0077ff",
  checkboxBorder: "#1a1a1a",
  checkboxCheckColor: "#fff",
  paginationBackground: "#2c2c2c",
  paginationText: "#fff",
  loadingSpinnerBorder: "#555",
  loadingSpinnerTopBorder: "#0077ff",
  linkText: "#0077ff",
  scrollbarThumb: "#aaa",
  scrollbarTrack: "#333",
  disabledBackground: "#eee",
  errorColor: "red",
  errorShadow: "rgba(255, 0, 0, 0.2)",
  dangerColor: "red",
  successColor: "#00cc00",
  infoColor: "#3399ff",
  warningColor: "#ffcc00",
  notificationBackground: "#1a1a1a",
};
